name: build_and_test

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Update pip/wheel infrastructure
        shell: bash -l {0}
        run: |
          mamba install -y -q pip wheel

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install uv
          uv pip install -r requirements.txt

      # We have two cores so we can speed up the testing with xdist
      - name: Install pytest packages
        shell: bash -l {0}
        run: |
          mamba install -y -q \
            pytest pytest-xdist pytest-openfiles pytest-cov

      - name: List installed packages
        shell: bash -l {0}
        run: |
          mamba list
          pip list -v

      - name: Build and install
        shell: bash -l {0}
        run: |
          uv pip install -v --no-deps -e .

      - name: Run tests
        shell: bash -l {0}
        env:
          SQLALCHEMY_WARN_20: 1
        run: |
          pytest -r a -v -n 3 --open-files --cov=lsst.shoefits --cov=tests --cov-report=xml --cov-report=term --cov-branch
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
